# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Surveys' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Surveys

  target 'SurveysTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SurveysUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
