# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Surveys' do

  # Pods for Surveys
  
  pod 'AFNetworking', '~> 3.0'
  pod 'AFOAuth2Manager', '~> 3.0'
  pod 'Toast', '~> 3.1'
  
  target 'SurveysTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SurveysUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
